version: '3'

services:
  database:
    image: postgres
    restart: always
    container_name: "database-food-services"
    environment:
      - POSTGRES_DB=food-services
      - POSTGRES_USER=food-services-admin
      - POSTGRES_PASSWORD=password123
    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data

  redis:
    container_name: "redis-food-services"
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  mongodb:
    image : mongo
    container_name: "mongodb-food-services"
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    restart: always
