version: '3'

services:

  auth:
    container_name: "auth-food-services"
    build:
      context: food-services-auth-node-backend
    ports:
      - "3000:3000"
    depends_on:
      - database-auth
      - redis
      - mongodb
    env_file:
      - .food-services-auth-node-backend.env

  database-auth:
    image: postgres
    restart: always
    container_name: "database-auth-food-services"
    environment:
      - POSTGRES_DB=food-services-auth
      - POSTGRES_USER=food-services-auth-admin
      - POSTGRES_PASSWORD=password123
    ports:
      - '54320:5432'
    volumes:
      - ./database/auth:/var/lib/postgresql/data

  recipes:
    container_name: "recipes-food-services"
    build:
      context: food-services-recipes-java-backend
    ports:
      - "8080:8080"
    depends_on:
      - database-recipes
      - redis
      - mongodb
    env_file:
      - .food-services-recipes-java-backend.env

  database-recipes:
    image: postgres
    restart: always
    container_name: "database-recipes-food-services"
    environment:
      - POSTGRES_DB=food-services-recipes
      - POSTGRES_USER=food-services-recipes-admin
      - POSTGRES_PASSWORD=password123
    ports:
      - '54321:5432'
    volumes:
      - ./database/recipes:/var/lib/postgresql/data

  redis:
    container_name: "redis-food-services"
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  mongodb:
    image : mongo
    container_name: "mongodb-food-services"
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - '27017:27017'
    restart: always

  rabbitmq:
    image: rabbitmq:3.12
    container_name: "rabbitmq-food-services"
    ports:
      - "5672:5672"

  rabbitmq-admin:
    image: rabbitmq:3.12-management
    container_name: "rabbitmq-admin-food-services"
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest