version: '3'

services:

  database-auth:
    image: postgres
    restart: always
    container_name: "database-auth-food-services"
    environment:
      - POSTGRES_DB=food-services-auth
      - POSTGRES_USER=food-services-auth-admin
      - POSTGRES_PASSWORD=password123
    ports:
      - '54320:5432'
    volumes:
      - ./database/auth:/var/lib/postgresql/data

  database-recipes:
    image: postgres
    restart: always
    container_name: "database-recipes-food-services"
    environment:
      - POSTGRES_DB=food-services-recipes
      - POSTGRES_USER=food-services-recipes-admin
      - POSTGRES_PASSWORD=password123
    ports:
      - '54321:5432'
    volumes:
      - ./database/recipes:/var/lib/postgresql/data

  redis:
    container_name: "redis-food-services"
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  mongodb:
    image : mongo
    container_name: "mongodb-food-services"
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - '27017:27017'
    restart: always

  rabbitmq-admin:
    image: rabbitmq:3.12-management
    container_name: "rabbitmq-admin-food-services"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest